version: '3.8'
services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    tty: true
    stdin_open: true
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local      
    volumes:
      - .:/code
      - poetry:/root/.cache/pypoetry
    depends_on:
      - database

  database:
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    volumes: 
      - db:/var/lib/postgresql/data    


volumes: 
  poetry:
  db:
