# fly.toml file generated for rm-django-demos on 2023-01-23T23:02:40-06:00

app = "rm-django-demos"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "Dockerfile"

  [build.args]
  GAMESTONE_API_URL = "https://rm-django-demos.fly.dev/gamestone/api/"

[deploy]
  release_command = "poetry run python manage.py migrate"

[env]
  DJANGO_SETTINGS_MODULE = "config.settings.prod"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
