version: '3.7'
services:
  app:
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ..
    container_name: django-docker-example
    image: gamestone-backend-dev:0.0.1
    tty: true
    stdin_open: true
    volumes:
      - ..:/app:delegated
      - .config:/root/.config
      - python:/python
    ports:
      - 8000:8000

volumes:
  python:
